version: "3"

networks:
  traefik-proxy:
    external: true

services:
  app:
    container_name: s3_monitoring
    image: "${INTERNAL_REG}/s3-monitoring:${APP_VERSION}-debug"
    build:
      context: .
      args:
        - APP_VERSION=${APP_VERSION}
        - PYTHON_IMG_TAG=${PYTHON_IMG_TAG}
        - MAINTAINER=${MAINTAINER}
        - EXTERNAL_REG=${EXTERNAL_REG}
        - INTERNAL_REG=${INTERNAL_REG}
      target: debug
    env_file:
      - .env.secret
    extra_hosts:
      - "verse.wsl.ch:10.30.1.65"
    networks:
      - traefik-proxy
    restart: unless-stopped
